// Team DAIX, 2026
// HYDRAULICPRESS — FileUtils
//
// The majority of this code was written between 2020 and 2022
//
// This module's purpose is to:
// 1. Locate and load the variable definition file (vars.txt / vars_bak.txt)
// 2. Parse variable entries into (name, value) pairs
// 3. Load lists of files with mismatched SHA hashes
// 4. Determine which .txt files should be processed by HydraulicPress
// 5. Provide small helpers for folder detection and file filtering
//
// Used during script compilation to read variables and identify files requiring replacement.

#include "FileUtils.h"
#include "StringUtils.h"
#include "../Common/Config.h"
#include <regex>

// Returns the path to the variable file used by HydraulicPress.
// Priority:
//   1. vars.txt (if present)
//   2. backup_path/vars_bak.txt (fallback)
// Example result: "DGRV3/vars_bak.txt"

std::string FileUtils::GetInputFile(std::filesystem::path const& backup_path) {

	// We want to check this file
	// Look for vars.txt first, then fallback to vars_bak.txt
	// Actually, vars.txt never existed in the first place and we never accounted for it in most other programs

	std::string vars_txt = EncryptString("vars.txt");

	std::ifstream in_vars(vars_txt, std::ios::in);

	// If vars.txt couldn't be read correctly / doesn't exist

	if (!in_vars.good()) {
		// vars.txt does not exist → fall back to vars_bak.txt inside the repo.

		LOG("WARNING: Could not find vars.txt!", HERE, "HydraulicPress");

		// Use backup file from repo

		vars_txt = (backup_path / EncryptString("vars_bak.txt")).string();

		in_vars = std::ifstream(vars_txt, std::ios::in);

		if (!in_vars.good()) {

			LOG("ERROR: vars_bak.txt couldn't be read correctly!", HERE, "HydraulicPress");
			return "";
		}

		// In this case, vars_bak.txt could be red correctly
		LOG("Using backup from the repository!", HERE, "HydraulicPress");
	}

	in_vars.close();

	return vars_txt;
}

// Loads the list of files with mismatched SHA hashes (generated by Necronomicon).
// Each line is relative; convert to absolute paths.
// Example input line: "chapter3/scene_12.txt"

std::vector<std::string> FileUtils::ReadDifferentHashesFile(std::string const& filename) {

	if (!std::filesystem::exists(filename)) {
		return {};
	}

	std::ifstream infile(filename, std::ios::in);
	std::string temp{};
	std::vector<std::string> ret{};
	std::filesystem::path cur = std::filesystem::current_path();
	while (std::getline(infile, temp)) {
		std::filesystem::path const p(cur / temp);
		ret.push_back(p.string());
	}
	infile.close();
	return ret;
}

// Parses the variable file (vars.txt or vars_bak.txt).
// Each line defines a variable in the format:
//     NAME, VALUE
// Supports special cases:
//     - <CLT...> variables without commas
//     - SIGNAL_* markers
//     - IceConvention mode for colon-based values

std::vector<VarEntry> FileUtils::ReadInputFile(std::string const& input_file) {

	// This is the vector where our variables go in
	std::vector<VarEntry> variables{};

	// ✅ Early exit if no file path was provided
	if (input_file.empty()) {
		LOG("ERROR: No input file path provided to ReadInputFile()", HERE, "HydraulicPress");
		return variables; // return empty vector
	}

	// This is a temporary std::string to store the red line from the file
	std::string temp{};

	std::ifstream in_vars(input_file, std::ios::in);

	while (std::getline(in_vars, temp)) {
		// We don't care about empty lines
		if (temp.empty()) {
			continue;
		}

		if (temp.front() == '\n' || temp.front() == '\r') {
			continue;
		}

		// Find commented out lines (starting with /)
		if (temp.front() == '/') {
			continue;
		}

		// Find variable comments
		// If the line starts with a variable comment... Continue? This shouldn't happen
		if (temp.front() == '|' || temp.starts_with("| ") || temp.starts_with(" |")) {
			continue;
		}

		// Remove trailing variable comments:
		// Example: "VAR_NAME, VALUE | comment" → "VAR_NAME, VALUE"

		std::size_t const pipe_position = temp.find('|');
		// Pipe position can't be zero
		if (pipe_position != std::string::npos) {
			// Remove variable comment if it exists
			temp = temp.substr(0, pipe_position - 1);
		}

		if (temp.length() <= 2) {
			continue;
		}

		// Find the first comma
		std::size_t const find_comma = temp.find(",");
		// If the comma isn't found
		if (find_comma == std::string::npos) {
			// Lines without commas may define CLT variables.
			// Example: "<CLT_SOMETHING>" → MV("<CLT_SOMETHING>", "")

			// And the std::string contains <CLT
			if (Common::StringContains(temp, "<CLT")) {
				// Then add it to the variables
				variables.push_back(MV(temp, ""));
			}
			else {
				LOG("WARNING: Ignored variable: " + temp, HERE, "HydraulicPress");
			}
			continue;
		}

		// Get the name of the variable (not the value)
		// by only reading from the start of the std::string
		// to the position of the comma
		std::string const vars = temp.substr(0, find_comma);

		// The temporary line's length
		// shouldn't contain only one character after the comma...?
		// This is probably a mistake, but
		// it's not going to be used probably
		// so I'll just leave it here
		if (temp.length() <= (find_comma + 1)) {
			continue;
		}

		// std::string for containing the value of the variable
		// (not the name)
		std::string value = "";

		// Determine how to extract the variable value:
		// - If no colon or SIGNAL present → everything after comma
		// - If colon exists and IceConvention = true → take substring before colon
		// - Otherwise → take substring after colon

		// Find the first colon
		std::size_t find_colon = temp.find(":");
		// Is this a signal?
		std::size_t const find_sig = temp.find(EncryptString("SIGNAL"));
		// If it's not found
		if (find_colon == std::string::npos || find_sig != std::string::npos || find_colon < (find_comma + 1 + 1)) {
			// Then the value of the variable is everything
			// there is after the comma

			// If *NOT* SIGNAL_OE
			if (!Common::StringContains(temp, "<SIGNAL_OE>")) {
				value = temp.substr(find_comma + 1 + 1);
			}
		}
		else {
			// If you're here: a colon was found
			
			// If we choose not to use our terminology
			if (Configuration::ConfigMap["UseIceConvention"]) {
				// Create a substring without the characters
				// before the comma, so only the ones
				// after the comma remain
				value = temp.substr(find_comma + 1 + 1);

				// Find the colon
				find_colon = value.find(":");

				// Create a substring from the start
				// of the std::string to the colon
				value = value.substr(0, find_colon - 1);
			}
			else {

				// Then the value is everything after the colon
				value = temp.substr(find_colon + 1 + 1);
			}
		}

		// Add to the variables
		variables.push_back(MV(vars, value));
	}

	// Close the input file
	in_vars.close();

	// Strip CR/LF characters from both name and value to avoid hidden formatting issues.

	for (auto& var : variables) {
		var.first = std::regex_replace(var.first, std::regex("\r"), "");
		var.first = std::regex_replace(var.first, std::regex("\n"), "");
		var.second = std::regex_replace(var.second, std::regex("\r"), "");
		var.second = std::regex_replace(var.second, std::regex("\n"), "");
	}

	return variables;
}

// Determines which .txt files HydraulicPress should process.
// If CheckAllFiles = true → scan entire repo
// Otherwise → only files listed in different_hashes.txt

std::vector<std::string> FileUtils::GetFilesToSearch(std::filesystem::path const& search_path) {

	std::vector<std::string> file_to_search{};

	// Now it's time to check every file, see if they contain
	// replaceable strings
	// Equivalent of "bool all" from Electrohammer
	if (Configuration::ConfigMap["CheckAllFiles"]) {
		for (auto const& file : std::filesystem::recursive_directory_iterator(search_path)) {

			if (!IsFileGood(file.path().string())) {
				continue;
			}

			// Add the .txt to the files that could contain the replaceable std::string(s)
			file_to_search.push_back(file.path().string());
		}
	}
	else {
		auto const vec = FileUtils::ReadDifferentHashesFile("different_hashes.txt");
		for (auto const& file : vec) {
			if (!IsFileGood(file)) {
				continue;
			}

			// Add the .txt to the files that could contain the replaceable std::string(s)
			file_to_search.push_back(file);
		}
	}

	return file_to_search;
}

// Filters out non-script files:
// - README, LICENSE, .git, backups, SHA files, PB files
// - vars_bak.txt (variable file)
// Only actual .txt script files should be processed.


bool FileUtils::IsFileGood(std::string const& file) {

	// If the file isn't a .txt, continue

	if (!Common::StringContains(file, ".txt")) {
		return false;
	}

	if (Common::StringContains(file, "_sha")) {
		return false;
	}
	if (Common::StringContains(file, "_lines")) {
		return false;
	}
	if (Common::StringContains(file, "README")) {
		return false;
	}
	if (Common::StringContains(file, "LICENSE")) {
		return false;
	}
	if (Common::StringContains(file, ".git")) {
		return false;
	}
	if (Common::StringContains(file, "Baked")) {
		return false;
	}

	if (Common::StringContains(file, ".pb")) {
		return false;
	}

	if (file.empty()) {
		return false;
	}

	// It can't be the file with the variables
	if (Common::StringContains(file, EncryptString("vars_bak"))) {
		return false;
	}

	return true;
}

// Returns the folder name containing the given file.
// Example: "DGRV3/chapter3/scene_12.txt" → "chapter3"

std::string FileUtils::GetContainingFolder(std::string const& full_path) {

	std::filesystem::path const p = std::filesystem::path(full_path).parent_path();
	std::string const str = p.filename().string();
	return str;
}