// Team DAIX, 2026
// MONOKID — FONTTOOLS DISTRIBUTION FILTER

// The majority of this code was written between 2020 and 2022

// This tool's purpose is:
// Monokid prepares the final distribution folder for FontTools by filtering,
// cleaning, and copying only the SPC font archives that were actually modified
// during compilation. It performs:
//
//   • Cleanup of empty files inside base_fonts and base_fonts_copy
//   • Reading list_changed.txt (generated by Monodam)
//   • Matching SPC paths against the list of modified fonts
//   • Deleting all SPCs that were NOT modified
//   • Copying the remaining SPCs into ModifiedFiles-Font
//
// Monokid is the “distribution stage” of FontTools. It ensures that only
// modified font SPCs are included in the final output, preventing accidental
// redistribution of untouched copyrighted assets.


#include <iostream>
#include <string>
#include <vector>
#include <filesystem>
#include <fstream>
#include <thread>
#include <chrono>
#include <regex>

#ifdef _WIN32
#include <Windows.h>
#endif

#include "../Common/Common.h"

int main() {

	std::string const repo = EncryptString("DGRV3-Font");

	std::filesystem::path const current_dir = std::filesystem::current_path();
	std::filesystem::path const dist = current_dir / EncryptString("ModifiedFiles-Font");
	std::filesystem::path const dgrv3path = current_dir / repo;
	std::filesystem::path const where = (dgrv3path / EncryptString("base_spc"));
	std::filesystem::path const nested_spc = where / "base_fonts";
	std::filesystem::path const copy = where / "base_fonts_copy";

	if (!std::filesystem::exists(where)) {
		LOG("ERROR: The folder to copy from was not found!", HERE, "Monokid");
		return -1;
	}

	if (std::filesystem::exists(dist)) {
		LOG("WARNING: Distribution folder already exists, deleting old one...", HERE, "Monokid");
		std::filesystem::remove_all(dist);
	}
	else {
		std::filesystem::create_directories(dist);
	}

	std::vector<std::string> removec{};

	// base-fonts
	// Remove empty files from base_fonts?
	// These are artifacts left behind by HTFont or SpcTool and should not be distributed?

	for (auto const& file : std::filesystem::recursive_directory_iterator(nested_spc)) {

		if (!file.is_directory() && std::filesystem::is_empty(file)) {
			removec.push_back(file.path().string());
		}
	}

	for (auto const& f : removec) {
		LOG("[1] Deleting " + f, HERE, "Monokid");
		std::filesystem::remove_all(f);
	}

	removec.clear();

	// base-fonts-copy
	// Remove empty files from base_fonts_copy?
	// This folder mirrors base_fonts and must be cleaned consistently?

	for (auto const& file : std::filesystem::recursive_directory_iterator(copy)) {

		if (!file.is_directory() && std::filesystem::is_empty(file)) {
			removec.push_back(file.path().string());
		}
	}

	for (auto const& f : removec) {
		LOG("[2] Deleting " + f, HERE, "Monokid");
		std::filesystem::remove_all(f);
	}

	// Read list_changed.txt generated by Monodam.
	// Each entry corresponds to an SPC that was modified during font compilation.

	std::vector<std::string> list_changed{};
	std::ifstream in("list_changed.txt", std::ios::in);
	std::string temp{};
	while (std::getline(in, temp)) {
		std::filesystem::path const fp(dgrv3path / temp);
		std::string file = fp.string();
		LOG("Found in txt: " + file, HERE, "Monokid");
		if (std::filesystem::exists(file)) {
			LOG("File exists!", HERE, "Monokid");
			std::replace(file.begin(), file.end(), '\\', '|');
			std::replace(file.begin(), file.end(), '/', '|');
			file = file.substr(0, file.length() - fp.extension().string().length());
			LOG("Adding file to the list: " + file, HERE, "Monokid");
			list_changed.push_back(file);
		}
		else {
			LOG("WARNING: File does not exist!", HERE, "Monokid");
		}
	}
	in.close();

	// For each SPC in base_fonts:
	//   • Normalize its path
	//   • Check if it appears in list_changed
	//   • If not, delete it (it was not modified)

	for (auto const& file : std::filesystem::recursive_directory_iterator(nested_spc)) {

		if (file.is_directory()) {
			continue;
		}

		std::string temp = file.path().string();
		std::replace(temp.begin(), temp.end(), '\\', '|');
		std::replace(temp.begin(), temp.end(), '/', '|');
		temp = temp.substr(0, temp.length() - file.path().extension().string().length());

		auto const it = std::find(list_changed.begin(), list_changed.end(), temp);
		bool const found = it != list_changed.end();

		if (!found) {
			LOG("[3] Deleting " + file.path().string() + " because " + temp + " isn't in the list!", HERE, "Monokid");
#ifdef _WIN32
			DeleteFileA(file.path().string().c_str());
#else
			Common::executeBatch(("rm " + file.path().string()).c_str());
#endif
		}
		else {
			LOG("File *not* deleted: " + file.path().string(), HERE, "Monokid");
		}
	}

	// Copy the filtered base_fonts directory into ModifiedFiles-Font.
	// Only SPCs that were actually modified are included in the final distribution.

	std::filesystem::copy(nested_spc, dist, std::filesystem::copy_options::recursive | std::filesystem::copy_options::overwrite_existing);

	LOG("All files copied in the distribution folder!", HERE, "Monokid");

	Common::WaitExit();
}