// Team DAIX, 2026
// CROSSBOW — Modified SPC Distributor
//
// The majority of this code was written between 2020 and 2022
//
// This tool's purpose is to:
// 1. Read different_hashes.txt (generated by Necronomicon)
// 2. Determine which SPC/PB files have been modified
// 3. Copy only those modified files into either:
//      - ModifiedFiles/   (normal mode)
//      - Distribute/      (part2 mode)
// 4. Handle special trial files (hanron, nonstop, panic, kokoronpa, nico)
// 5. Map SPC filenames to correct output directories (game_resident, wrd_data, wrd_script/<rev>, master)
// 6. Rename FR trial files to US equivalents in part2 mode
// 7. Clean leftover files in Distribute/ after copying
//
// Crossbow is the final “distribution” stage: it extracts only the changed SPC/PB files
// so they can be packaged, tested, or shipped without copying the entire base_spc folder.

#include <iostream>
#include <string>
#include <vector>
#include <filesystem>
#include <fstream>
#include <thread>
#include <chrono>
#include <utility>
#include <algorithm>
#include <regex>

// What?
#define DISTRIBUTE

#ifdef _WIN32
#include <Windows.h>
#endif

#include "../Common/Common.h"

// Maps SPC filename prefixes → chapter/folder names.
// Used to determine whether a file belongs to a logged (changed) chapter.

std::vector<std::pair<std::string, std::string>> chapters {
	{ "chap0", "prologue" },
	{ "chap1", "chapter1" },
	{ "chap2", "chapter2" },
	{ "chap3", "chapter3" },
	{ "chap4", "chapter4" },
	{ "chap5", "chapter5" },
	{ "chap6", "chapter6" },
	{ "chap7", "epilogue" },
	{ "map_obj_name_text", "MapObjName" },
	{ "game_resident", "game_resident" },
	{ "gallery", "gallery" },
	{ "ainori", "ainori" },
};

// List of chapter names that contain modified files.
// Populated from different_hashes.txt.

std::vector<std::string> logged{};

bool ShouldBeSaved(std::string const& filename);
void LoadLoggedFromFile(const std::string& filename);

int main(int argc, char* argv[]) {

	// part2 mode: special distribution rules for trial files and Distribute/ folder.

	bool part2 = false;

	if (argc > 1 && argv[1] && strcmp(argv[1], EncryptString("part2")) == 0) {
		part2 = true;
	}
	if (argc > 2 && argv[2] && strcmp(argv[2], EncryptString("part2")) == 0) {
		part2 = true;
	}

	if (part2) {
		LOG("Crossbow Part2", HERE, "Crossbow");
	}

	std::string const repo = EncryptString("DGRV3");
	std::string const repo_en = EncryptString("DGRV3_EN");

	std::filesystem::path const current_dir = std::filesystem::current_path();
	std::filesystem::path const dist = current_dir / EncryptString("ModifiedFiles");
	std::filesystem::path const actualdist = current_dir / EncryptString("Distribute");
	std::filesystem::path const dgrv3path = current_dir / repo;
	std::filesystem::path const where = (dgrv3path / EncryptString("base_spc"));


	if (!std::filesystem::exists(dgrv3path)) {
		LOG("ERROR: Repo folder not found: " + dgrv3path.string(), HERE, "Crossbow");
		return -1;
	}
	if (!std::filesystem::exists(where)) {
		LOG("ERROR: base_spc folder not found: " + where.string(), HERE, "Crossbow");
		return -1;
	}

	LoadLoggedFromFile((current_dir / "different_hashes.txt").string());

	/*
	if (std::filesystem::exists(dist)) {
		std::cout << "Distribution folder already exists, deleting old one..." << std::endl;
		std::filesystem::remove_all(dist);
	}
	*/

	std::vector<std::string> modified{};

	auto dir = part2 ? actualdist : where;

	// dist = ModifiedFiles/
	// actualdist = Distribute/
	// where = DGRV3/base_spc/
	// dir = folder to scan (depends on part2)

	LOG("Iterating through " + dir.string(), HERE, "Crossbow");

	// Iterate through all SPC/PB files in the selected directory.
	// In part2 mode, only scan top-level files (depth = 0).

	for (auto it = std::filesystem::recursive_directory_iterator(dir);
		it != std::filesystem::recursive_directory_iterator(); ++it)
	{
		if (part2 && it.depth() > 0) {
			it.disable_recursion_pending();
			continue;
		}

		const auto& file = *it;
		if (file.is_directory()) continue;

		if (file.path().string().length() <= 3) { // C:/
			continue;
		}

		// Only SPC and PB files are relevant.
		// Ignore everything else (TXT, STX, extracted folders, etc.).

		auto ext = file.path().extension().string();
		std::transform(ext.begin(), ext.end(), ext.begin(),
			[](unsigned char c) { return static_cast<char>(std::tolower(c)); });

		if (ext != ".spc" && ext != ".pb") {
			LOG("Ignoring file: " + file.path().string(), HERE, "Crossbow");
			continue;
		}

		// Skip files inside *_extracted folders — these are temporary extraction outputs?

		if (file.path().string().contains("_extracted")) {
			continue;
		}

		// A file is considered modified if:
		// - Its chapter is in `logged`
		// - OR it is a PB file (always copied)
		// In part2 mode, trial files are handled separately.

		bool has_been_modified = ShouldBeSaved(file.path().filename().string()) || file.path().extension() == ".pb";

		if (has_been_modified) {
			modified.push_back(file.path().string());
		}
	}

	LOG("Hard part is over", HERE, "Crossbow");

	if (!std::filesystem::exists(dist)) {
		std::filesystem::create_directory(dist);
	}

	if (part2) {
		// Trial files (hanron, nonstop, panic, kokoronpa, nico) require special handling.
		// Only FR versions are copied in part2 mode.

		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "hanron_01_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "hanron_02_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "hanron_03_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "hanron_04_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "hanron_05_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "hanron_06_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "kokoronpa_08_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "nico_06_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "nonstop_01_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "nonstop_02_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "nonstop_03_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "nonstop_04_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "nonstop_05_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "nonstop_06_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "panic_01_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "panic_02_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "panic_03_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "panic_04_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "panic_05_FR.spc").string());
		modified.push_back(std::filesystem::path(where / "trial_french_extracted" / "panic_06_FR.spc").string());
	}

	bool allCopied = true; // track overall success
	static const std::string latest_game_revision = "007";

	// Map SPC filenames to correct output folders:
	// - game_resident → game_resident/
	// - map_obj_name_text → wrd_data/
	// - trial files → wrd_data/
	// - everything else → wrd_script/<latest_game_revision>/
	// PB files → master/

	for (auto const& j : modified) {

		LOG("Doing: " + j, HERE, "Crossbow");

		if (j.length() <= 3) { // C:/
			LOG("Empty file: " + j, HERE, "Crossbow");
			continue;
		}

		std::filesystem::path const f(j);

		bool const is_trial_file = 
			(j.contains(".spc") || j.contains(".SPC")) && 
			(j.contains("hanron_") || j.contains("kokoronpa_08_") || j.contains("nico_06_") || j.contains("nonstop_") || j.contains("panic_"));

		if (is_trial_file && !f.filename().string().contains("_FR")) {
			continue;
		}

		std::string filepath = (j.contains(".spc") || j.contains(".SPC") ? (j.contains("game_resident") ? ("game_resident") : (j.contains("map_obj_name_text") || is_trial_file ? ("wrd_data") : ((std::filesystem::path("wrd_script") / latest_game_revision).string()))) : ("master"));

		auto const file_name = f.filename().string();
		std::filesystem::path dest{};
		if (!is_trial_file) {
			dest = part2 ? (actualdist / filepath / file_name) : (dist / filepath / file_name);
		}
		else {
			if (!part2) {
				continue;
			}
			dest = (dist / filepath / std::regex_replace(file_name, std::regex("FR"), "US"));
		}

		if (!std::filesystem::exists(f)) {
			LOG("File does not exist: " + f.string(), HERE, "Crossbow");
			continue;
		}
		std::error_code ec;
		if (std::filesystem::exists(dest) &&
			std::filesystem::equivalent(f, dest, ec) && !ec) {
			LOG("Skipping copy: source and destination are the same", HERE, "Crossbow");
			continue;
		}

		std::filesystem::create_directories(dest.parent_path());

		LOG("Copying \"" + f.string() + "\" to \"" + dest.string() + "\"...", HERE, "Crossbow");

		if (std::filesystem::exists(dest)) {
			LOG("Destination already exists: " + dest.string(), HERE, "Crossbow");
		}

		// Copy modified SPC/PB files into the destination folder.
		// Uses platform-specific copy methods (std::filesystem, CopyFileA, cp).

#ifdef CPP20
		try {
			allCopied &= std::filesystem::copy_file(f, dest, std::filesystem::copy_options::overwrite_existing);
		}
		catch (std::filesystem::filesystem_error ec) {
			LOG("ERROR: Failed to copy \"" + f.string() + "\" to \"" + dest.string() + "\": " + ec.what(), HERE, "Crossbow");
		}
#else
#ifdef _WIN32
		if (!CopyFileA(f.string().c_str(), dest.string().c_str(), FALSE)) {
			DWORD err = GetLastError();
			LOG("ERROR: Failed to copy \"" + f.string() + "\". Win32 error code: " + std::to_string(err),
				HERE, "Crossbow");
			allCopied = false;
		}
#else
		std::string const command = "cp \"" + f.string() + "\" \"" + dest.string() + "\"";
		int ret = Common::executeBatch(command.c_str());
		if (ret != 0) {
			LOG("ERROR: Failed to copy \"" + f.string() + "\". Command returned: " + std::to_string(ret),
				HERE, "Crossbow");
			allCopied = false;
		}
#endif
#endif
	}


	if (allCopied && !modified.empty()) {
		std::string const str = "All files copied in the " + std::string{ part2 ? "Distribute" : "ModifiedFiles" } + " folder!";
		LOG(str, HERE, "Crossbow");
	}
	else if (!allCopied) {
		LOG("Some files failed to copy. Check the log for details.", HERE, "Crossbow");
	}

	if (!modified.empty()) {
		std::ofstream out(EncryptString("file_copied.txt"), std::ios::out | std::ios::app);
		for (auto const& j : modified) {
			out << Common::ShortenFilename(j, 2) << std::endl;
		}
		out.close();
	}

	// In part2 mode, remove leftover files from Distribute/ that were not copied.
	// Ensures the folder contains only the final distribution set.

	if (part2 && !modified.empty()) {
		LOG("Removing leftovers", HERE, "Crossbow");
		std::vector<std::string> todelete{};

		for (auto const& ff : std::filesystem::directory_iterator(actualdist)) {
			if (ff.is_directory()) {
				continue;
			}

			todelete.push_back(ff.path().string());
		}

		for (auto const& td : todelete) {
			try {
				LOG("Removing leftover: " + td, HERE, "Crossbow");
				std::filesystem::remove(td);
			}
			catch (std::filesystem::filesystem_error ec) {
				LOG("Couldn't delete leftover: " + td + " -- " + ec.what(), HERE, "Crossbow");
			}
		}
	}

#ifndef DISTRIBUTE
	// std::filesystem::remove("tempfile.exe");
#endif

	Common::WaitExit();
}

// Returns true if the SPC filename belongs to a chapter listed in `logged`.
// Also removes the chapter from `logged` once matched (one-time consumption).

bool ShouldBeSaved(std::string const& filename) {
	auto it = std::find_if(chapters.begin(), chapters.end(),
		[&](auto const& x) {
		return filename.find(x.first) != std::string::npos &&
			std::find(logged.begin(), logged.end(), x.second) != logged.end();
	});

	if (it != chapters.end()) {
		LOG("Removing " + it->second + " from logged", HERE, "Crossbow");
		// Remove the found x.second from logged
		logged.erase(std::remove(logged.begin(), logged.end(), it->second), logged.end());
		return true;
	}
	else {
		LOG(filename + ": NOT in logged", HERE, "Crossbow");
	}

	return false;
}

// Reads different_hashes.txt and extracts chapter names that contain modified files.
// Only stores chapter names (not filenames).

void LoadLoggedFromFile(const std::string& filename) {

	LOG("Loading hashes from file...", HERE, "Crossbow");

	std::ifstream file(filename);
	if (!file) {
		std::cerr << "Error: Could not open " << filename << "\n";
		return;
	}

	std::string line;
	while (std::getline(file, line)) {
		for (const auto& ch : chapters) {
			// ch.second is the value we want to check for
			if (line.contains(ch.second)) {
				// Only add if not already in logged
				if (std::find(logged.begin(), logged.end(), ch.second) == logged.end()) {
					logged.push_back(ch.second);
				}
			}
		}
	}

	LOG("Hashes loaded:", HERE, "Crossbow");

	for (auto const& logg : logged) {
		LOG("\t" + logg, HERE, "Crossbow");
	}
}